### ISSUE TITLE
`html_meta` and `substitutions` topmatter keys deprecated, moved under `myst` key

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1263]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

The release of myst-parser 0.18.0 on 2022-06-07 introduced a breaking change. From https://myst-parser.readthedocs.io/en/latest/develop/_changelog.html#breaking-changes

> The top-level `html_meta` and `substitutions` top-matter keys have also been deprecated (i.e. they will still work but will emit a warning), as they now form part of the `myst` config, e.g.

```
html_meta:
  "description lang=en": "metadata description"
substitutions:
  key1: I'm a **substitution**
```

is replaced by:

```
myst:
  html_meta:
    "description lang=en": "metadata description"
  substitutions:
    key1: I'm a **substitution**
```

This will need to be pushed out to all other repos that are imported by this one, as well as training.

- [x] documentation
- [x] plone.api
- [x] plone.restapi
- [x] volto
- [x] training

Related issues:

- https://github.com/plone/documentation/issues/1147
- https://github.com/plone/documentation/issues/1243
