### ISSUE TITLE
Issue template: better not use task list.

### ISSUE THREAD

**Issue by jensens** [plone/documentation#1430]
### Plone Documentation versions affected

- [ ] 5.x
- [ ] 6.x

### Description

In Github now every task looks like half baken at progress indicator:

![screenshot_2023-01-16_00:57:09_selection](https://user-images.githubusercontent.com/157140/212574551-9772844a-6680-4506-bf15-37be945aae41.png)

**Comment by stevepiercy** [comment]
Yeah, it is a good idea, but I think we should revisit the implementation because of that reason and a few others.

The original problem was that we were getting issues submitted for 5 or 6 or both, and we had no idea what they were talking about. We have not been getting any for 5 for several months.

I think we can change that field, and clean up the Description, as follows. Hopefully we get a little more useful information.

### Existing

```yaml
  - type: checkboxes
    id: plone-versions
    attributes:
      label: Plone Documentation versions affected
      options:
        - label: 5.x
        - label: 6.x
  - type: textarea
    id: description
    attributes:
      label: Description
      description: If relevant, please include links to the affected resources, screenshots, and any other helpful information.
    validations:
      required: true
```

### Proposed

```yaml
  - type: textarea
    id: documentation-url
    attributes:
      label: Links of affected pages in Plone Documentation, if any.
      value: |
        - Link_1
        - Link_2
        - ...
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please include screenshots and any other helpful information.
    validations:
      required: true
```

Links would be optional, as it might not be a page.
