### ISSUE TITLE
Create a new top to link to other plone site to match new plone.org and community

### ISSUE THREAD

**Issue by martior** [plone/documentation#606]
html:

``` html
<div class="topbar">
            <div class="topcontainer">
              <ul id="links-select">
                <li>
                  <a href="https://plone.org" title="Main Website">
                    plone.org
                  </a>
                </li>
                <li>
                  <a href="http://plone.com" title="Plone.com">
                    plone.com
                  </a>
                </li>
                <li>
                  <a href="http://training.plone.org" title="Training">
                    training.plone.org
                  </a>
                </li>
                <li>
                  <a href="http://docs.plone.org" title="Documentation">
                    docs.plone.org
                  </a>
                </li>
              </ul>
            </div>
          </div>
```

css:

``` css
.topbar{
font-size: 11px;
font-weight: 600;
text-transform: uppercase;
background: #1f1238;
width: 100%;
overflow: hidden;
border-bottom: 1px solid black;
}          
.topcontainer{
margin-right: auto;
margin-left: auto;
padding-left: 15px;
padding-right: 15px
}
@media (min-width: 968px){
.topcontainer{
  width: 750px;
  }
}
@media (min-width: 992px){
.topcontainer{
  width: 970px;
  }
}
@media (min-width: 1200px){
.topcontainer{
  width: 1170px;
  }
}
.topbar ul{
  margin-right: 2.5em;
  float: right;
  margin: 0;
  padding: 0;
  list-style: none;
}
.topbar ul li{
  float: left;
}
.topbar a{
color: #e5e5e5;
text-decoration: none;
padding: 7px 8px 5px 8px;
line-height: 11px;
display: inline-block;
font-family: Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
font-size: 11px;
font-weight: 600;
}
.topbar a:hover{
color: #fff;
background: #2a184b;
}
```
